--station/station
DELETE FROM Prelevement;
DELETE FROM Mesurement;
DELETE FROM CuveReference;
DELETE FROM Creance;
DELETE FROM ENCAISSEMENT;

DELETE FROM Stock;
DELETE FROM SaleInvoices;
DELETE FROM OrderItems;
DELETE FROM Orders;

-- dax/dax
DELETE FROM COMPTA_SOUS_ECRITURE;